name: Node.js CI/CD

on:
  push:
    branches: [ "webapp" ]
  pull_request:
    branches: [ "webapp" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install dependencies
      working-directory: ./DevOps_Project/webapp
      run: npm install

    - name: Run tests
      working-directory: ./DevOps_Project/webapp
      run: npm test
